server:
  port: 80

spring:
  application:
      name: GeekAdmin
  profiles:
      active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

